---
- name: Configure
  hosts: all
  become: yes
  tasks: 
    - name: Create user Alice
      user:
        name: alice
        state: present
    - name: Create user Bjorn
      user:
        name: bjorn
        state: present
    - name: Create file /tmp/exercise with content
      copy:
        content: "TF with Ansible integration"
        dest: /tmp/exercise
